"""Dump SQLite schema (tables and indexes) to `sql/schema_dump.sql`.

This script reads the schema from `data/bank_reviews.db` (or DB pointed by DATABASE_URL if sqlite)
and writes a schema-only SQL file. It is intended for quick exports when using the SQLite fallback.

Run:
  $env:DATABASE_URL = 'sqlite:///data/bank_reviews.db'
  python scripts/dump_schema_sqlite.py
"""
import os
from pathlib import Path
import sqlite3


def get_sqlite_path():
    # If DATABASE_URL points to sqlite:///file, extract path; otherwise default to data/bank_reviews.db
    db_url = os.environ.get('DATABASE_URL')
    if db_url and db_url.startswith('sqlite:'):
        # handle sqlite:///absolute/path or sqlite:///:memory:
        if db_url == 'sqlite://':
            return None
        # remove sqlite:// prefix
        path = db_url.split(':', 1)[1]
        # strip leading //
        path = path.lstrip('/')
        return Path(path)
    return Path('data/bank_reviews.db')


def main():
    db_path = get_sqlite_path()
    if db_path is None:
        print('No sqlite file path found (in-memory DB). Nothing to dump.')
        return
    if not db_path.exists():
        raise FileNotFoundError(f'SQLite DB not found at {db_path}')

    out_path = Path('sql/schema_dump.sql')
    out_path.parent.mkdir(parents=True, exist_ok=True)

    con = sqlite3.connect(str(db_path))
    cur = con.cursor()

    # fetch table and index creation statements (exclude sqlite internal tables)
    cur.execute("SELECT type, name, sql FROM sqlite_master WHERE type IN ('table','index') AND name NOT LIKE 'sqlite_%' ORDER BY type, name;")
    rows = cur.fetchall()

    with out_path.open('w', encoding='utf-8') as fh:
        fh.write('-- SQLite schema dump generated by scripts/dump_schema_sqlite.py\n')
        fh.write(f'-- Source DB: {db_path}\n\n')
        for typ, name, sql in rows:
            if sql is None:
                continue
            fh.write(sql.strip() + ';')
            fh.write('\n')

    con.close()
    print('Wrote schema dump to', out_path)


if __name__ == '__main__':
    main()
