-- SQLite schema dump generated by scripts/dump_schema_sqlite.py
-- Source DB: data\bank_reviews.db

CREATE TABLE banks (
	bank_id INTEGER NOT NULL, 
	bank_name VARCHAR NOT NULL, 
	app_name VARCHAR, 
	PRIMARY KEY (bank_id), 
	UNIQUE (bank_name)
);
CREATE TABLE reviews (
	review_id INTEGER NOT NULL, 
	bank_id INTEGER, 
	review_text TEXT, 
	rating INTEGER, 
	review_date DATETIME, 
	sentiment_label VARCHAR, 
	sentiment_score FLOAT, 
	source VARCHAR, 
	raw_review_id VARCHAR, 
	PRIMARY KEY (review_id), 
	FOREIGN KEY(bank_id) REFERENCES banks (bank_id) ON DELETE CASCADE
);
